{% set major_minor = "2.24" %}
{% set version = major_minor + ".31" %}

package:
  name: gtk2
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/gtk+/{{ major_minor }}/gtk+-{{ version }}.tar.xz
  sha256: 68c1922732c7efc08df4656a5366dcc3afdc8791513400dac276009b40954658

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - perl 5.22.2.1
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - atk
    - cairo
    - fontconfig
    - freetype
    - gdk-pixbuf
    - gettext
    - glib
    - gobject-introspection
    - graphite2
    - harfbuzz
    - icu
    - jpeg
    - libffi
    - libiconv
    - libpng
    - libtiff
    - libxml2
    - pango
    - pcre
    - pixman
    - xz
    - zlib

  run:
    - atk
    - cairo
    - fontconfig
    - freetype
    - gdk-pixbuf
    - gettext
    - glib
    - gobject-introspection
    - graphite2
    - harfbuzz
    - icu
    - jpeg
    - libffi
    - libiconv
    - libpng
    - libtiff
    - libxml2
    - pango
    - pcre
    - pixman
    - xz
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME             # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME              # [osx]
    - test -f ${PREFIX}/lib/libgtk-x11-2.0{{ SHLIB_EXT }}     # [linux]
    - test -f ${PREFIX}/lib/libgtk-quartz-2.0{{ SHLIB_EXT }}  # [osx]

about:
  home: https://developer.gnome.org/gtk/
  license: LGPL-2
  license_file: COPYING
  summary: Primary library used to construct user interfaces in GNOME applications.

extra:
  recipe-maintainers:
    - jakirkham
    - pkgw
