{% set major_minor = "2.24" %}
{% set version = major_minor + ".32" %}

package:
  name: gtk2
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/gtk+/{{ major_minor }}/gtk+-{{ version }}.tar.xz
  sha256: b6c8a93ddda5eabe3bfee1eb39636c9a03d2a56c7b62828b359bf197943c582e

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - make
    - pkg-config
    - perl
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - atk
    - cairo
    - fontconfig
    - freetype
    - gdk-pixbuf
    - gettext
    - glib
    - gobject-introspection
    - graphite2
    - harfbuzz
    - icu
    - jpeg
    - libffi
    - libiconv
    - libpng
    - libtiff
    - libxml2
    - pango
    - pcre
    - pixman
    - xz
    - zlib
  run:
    - atk
    - cairo
    - fontconfig
    - freetype
    - gdk-pixbuf
    - gettext
    - glib
    - gobject-introspection
    - graphite2
    - harfbuzz
    - icu
    - jpeg
    - libffi
    - libiconv
    - libpng
    - libtiff
    - libxml2
    - pango
    - pcre
    - pixman
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libgtk-x11-2.0{{ SHLIB_EXT }}  # [linux]
    - test -f ${PREFIX}/lib/libgtk-quartz-2.0{{ SHLIB_EXT }}  # [osx]

about:
  home: https://developer.gnome.org/gtk/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Primary library used to construct user interfaces in GNOME applications

extra:
  recipe-maintainers:
    - jakirkham
    - pkgw
