appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: eR5pxKLTThD7x1aK5bCwQqhyR6ptEM4ubXbG9k04/UkjEwploWlPIbPFdHLGycjNpPzJiJ2gkSUte+31p9PwiAgCcDk9cIvFDD8N6Jy1g/jKrUx/u7Z4lMhGPeQw1yfF4unKCnFzHGUzrHyv2Fid2tHuDl9gUyPd23Yxpn2MoG/N+Oatnr0LhVLDfNYHt+Wz1vnVJIelnMF197XiW13Ft+KmocsGUzcSvmS3dJ0+RW/Ml5TFZ+BFKL7FeBLsFHgTDvq8zH552w8PYibQwXii9CzaUcEYxAaG41XNOYRw/3eUbRnhDhBBBFX5tN70N1Cy5ZcLtsDyntK7tE6qgAIXvGLw59xYRffzsxX+ycshXk1P7kp50w3MaWu0ckljMA22D8QXw87P+qn8kh8wzQzzZhNmBCTbyGxklweFCsxYuLjZQbeJfoD+DoJhT4k04v7xNYZwi2lbtB6BVPpnT+rUkbflzUxWLwyCjTvBTavHJkQaQ6wF+9t9s3G+qZyzNHEZsE6kt29j8ZhMqWaCMMiYzybps5ieWPtmiG8CDjMFU9AWacXmVLMtOAYjK49NBYHIv2TXfWdPo5gMnfgN1zHJYL0qApgLyCNngDjeyOllJpPHfZDm34IYV62TSHCM8JWu74qVg3vT7uB4JpO+o9V/IPZLuVPDsX2EO5irx1jt8wk=}
